/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// amplifyPush --simpleにより、aws-exports.jsが再生成されていた
// https://dev.classmethod.jp/articles/add-amplify-auth-to-angular-app/

const awsmobile = {
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_n4mYmZHWa",
        "userPoolWebClientId": "q1c6v6vf93738tf5nslqp6712",
        "identityPoolId": "us-east-1:5c58fb9a-70e3-4a13-a1c1-97f20610d960"
    },
    "Storage": {
        "AWSS3": {
            "bucket": "filestoragestack-s3bucket64cb25af-dy3ude7xgve6",
            "region": "us-east-1"
        }
    },
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://3vxzz6r7krgsbf2rnpoyrpksw4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
};


export default awsmobile;
