/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_O6KxdDH5i",
        "userPoolWebClientId": "55l7944ns5v1rej9kgk0itoeje",
        "identityPoolId": "us-east-1:0a100646-aa2d-4148-883b-ba8f9e3edc19"
    },
    "Storage": {
        "AWSS3": {
            "bucket": "filestoragestack-s3bucket64cb25af-dg9c911stcng",
            "region": "us-east-1"
        }
    },
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ybf7l2kpgjgpfbmbnlf3r3jllu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",

};


export default awsmobile;
